# Config file for meame-speaker
# This file should contain important values which are dependent on other 
# systems, such as MEAME and the MEAME-DSP.
# Names are kept as they are for the sake of readability.
# ------------------------------------------------------------------------------

#TODO: What do these thing do?


# DSP register addresses, this on is in hexadecimal
# These should be the same as the ones in MEAME-DSP/FB_Example/registers.h
# ------------------------------------------------------------------------------

# HS1
HS1_BASE = 0x8000
BLANKING_EN1 = HS1_BASE + 0x150
BLANKING_EN2 = HS1_BASE + 0x154

# MAILBOX
MAIL_BASE = 0x1000
MAIL_BASE_END = 0x1FFC

# INSTRUCTIONS AND STIMULATION
SLAVE_INSTRUCTION_ID = 0x1000  # Value at 0x1000 should be incremented after
                               # completed call
MASTER_INSTRUCTION_ID = 0x1004
INSTRUCTION_TYPE = 0x1008

STIM_QUEUE_BASE = 0x100c
STIM_QUEUE_RUNNING = STIM_QUEUE_BASE + 0x0

STIM_QUEUE_GROUP = STIM_QUEUE_BASE + 0x4
STIM_QUEUE_PERIOD = STIM_QUEUE_BASE + 0x8
STIM_QUEUE_ELEC0 = STIM_QUEUE_BASE + 0xc
STIM_QUEUE_ELEC1 = STIM_QUEUE_BASE + 0x10

CFG_DEBUG_ELEC0 = STIM_QUEUE_BASE + 0x14
CFG_DEBUG_ELEC1 = STIM_QUEUE_BASE + 0x18

CFG_DEBUG_MODE0 = STIM_QUEUE_BASE + 0x1c
CFG_DEBUG_MODE1 = STIM_QUEUE_BASE + 0x20
CFG_DEBUG_MODE2 = STIM_QUEUE_BASE + 0x24
CFG_DEBUG_MODE3 = STIM_QUEUE_BASE + 0x28

CFG_DEBUG_DAC0 = STIM_QUEUE_BASE + 0x2c
CFG_DEBUG_DAC1 = STIM_QUEUE_BASE + 0x30
CFG_DEBUG_DAC2 = STIM_QUEUE_BASE + 0x34
CFG_DEBUG_DAC3 = STIM_QUEUE_BASE + 0x38

SHOTS_FIRED = STIM_QUEUE_BASE + 0x3c

ERROR_FLAG = STIM_QUEUE_BASE + 0x40
ERROR_START = STIM_QUEUE_BASE + 0x44
ERROR_END = STIM_QUEUE_BASE + 0x60
ERROR_ENTRIES = STIM_QUEUE_BASE + 0x64

STEP_COUNTER = STIM_QUEUE_BASE + 0x68

STIM_REQ1_ACTIVE = STIM_QUEUE_BASE + 0x6c
STIM_REQ1_PERIOD = STIM_QUEUE_BASE + 0x70
STIM_REQ1_NEXT_FIRING_TIMESTEP = STIM_QUEUE_BASE + 0x74

STIM_REQ2_ACTIVE = STIM_QUEUE_BASE + 0x78
STIM_REQ2_PERIOD = STIM_QUEUE_BASE + 0x7c
STIM_REQ2_NEXT_FIRING_TIMESTEP = STIM_QUEUE_BASE + 0x80

STIM_REQ3_ACTIVE = STIM_QUEUE_BASE + 0x84
STIM_REQ3_PERIOD = STIM_QUEUE_BASE + 0x88
STIM_REQ3_NEXT_FIRING_TIMESTEP = STIM_QUEUE_BASE + 0x8c

DEBUG1 = STIM_QUEUE_BASE + 0x90
DEBUG2 = STIM_QUEUE_BASE + 0x94
DEBUG3 = STIM_QUEUE_BASE + 0x9c

LOG_START = 0x1100
LOG_END = 0x1f00
LOG_ENTRIES = 0x1ff0

# STG
STIM_BASE = 0x9000

ELECTRODE_ENABLE = STIM_BASE + 0x158
ELECTRODE_ENABLE1 = STIM_BASE + 0x158
ELECTRODE_ENABLE2 = STIM_BASE + 0x15c

ELECTRODE_MODE = STIM_BASE + 0x120
ELECTRODE_MODE1 = STIM_BASE + 0x120
ELECTRODE_MODE2 = STIM_BASE + 0x124
ELECTRODE_MODE3 = STIM_BASE + 0x128
ELECTRODE_MODE4 = STIM_BASE + 0x12c

ELECTRODE_DAC_SEL = STIM_BASE + 0x160
ELECTRODE_DAC_SEL1 = STIM_BASE + 0x160
ELECTRODE_DAC_SEL2 = STIM_BASE + 0x164
ELECTRODE_DAC_SEL3 = STIM_BASE + 0x168
ELECTRODE_DAC_SEL4 = STIM_BASE + 0x16c

TRIGGER_REPEAT1 = STIM_BASE + 0x190
TRIGGER_REPEAT2 = STIM_BASE + 0x194
TRIGGER_REPEAT3 = STIM_BASE + 0x198

STG_MWRITE1 = STIM_BASE + 0xf20
STG_MWRITE2 = STIM_BASE + 0xf24 
STG_MWRITE3 = STIM_BASE + 0xf28
STG_MWRITE4 = STIM_BASE + 0xf2c
STG_MWRITE5 = STIM_BASE + 0xf30
STG_MWRITE6 = STIM_BASE + 0xf34
STG_MWRITE7 = STIM_BASE + 0xf38
STG_MWRITE8 = STIM_BASE + 0xf3c

STG_MCLEAR_AND_WRITE1 = STIM_BASE + 0xf40
STG_MCLEAR_AND_WRITE2 = STIM_BASE + 0xf44
STG_MCLEAR_AND_WRITE3 = STIM_BASE + 0xf48
STG_MCLEAR_AND_WRITE4 = STIM_BASE + 0xf4c
STG_MCLEAR_AND_WRITE5 = STIM_BASE + 0xf50
STG_MCLEAR_AND_WRITE6 = STIM_BASE + 0xf54
STG_MCLEAR_AND_WRITE7 = STIM_BASE + 0xf58
STG_MCLEAR_AND_WRITE8 = STIM_BASE + 0xf5c

# TRIGGERS
TRIGGER_CTRL_BASE = 0x0200
TRIGGER_CTRL = TRIGGER_CTRL_BASE

MANUAL_TRIGGER = TRIGGER_CTRL_BASE + 0x14

#Electrode groups
ELEC_GRP_0 = 0x0 
ELEC_GRP_1 = 0x1 
ELEC_GRP_2 = 0x2 
